export const SERVERS_GET_REQUEST = 'SERVERS_GET_REQUEST';
export const SERVERS_GET_REQUEST_SUCCESS = 'SERVERS_GET_REQUEST_SUCCESS';
export const SERVERS_GET_REQUEST_FAILED = 'SERVERS_GET_REQUEST_FAILED';

export const PINGS_GET_REQUEST = 'PINGS_GET_REQUEST';
export const PINGS_GET_REQUEST_SUCCESS = 'PINGS_GET_REQUEST_SUCCESS';
export const PINGS_GET_REQUEST_FAILED = 'PINGS_GET_REQUEST_FAILED';